################################################################
# sysctl tunables for hardening file system hard and soft links
################################################################

fs.protected_hardlinks = 1
fs.protected_symlinks = 1
