#### MODIFY STATUS LINE
set -g status-right "%H:%M"
set -g window-status-current-style "underscore"

#### CHANGE TERMINAL STATUS LINE COLOR
%if #{TMUX}
  set -g status-bg red
%endif

#### STATUS LINE CONFIG
set -g status-position "bottom"

#### SET TERMINAL SETTINGS && COLOR PALETTE
set-option -sa terminal-features ",xterm*:RGB"
set -g default-terminal "xterm-256color"

#### DISABLE BELL SOUND
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

#### KEEP WINDOWS IN-MEMORY after they exit
set -g remain-on-exit off

#### REBIND PREFIX
set -g prefix M-f
bind M-f send-prefix
unbind C-b

#### BIND RELOAD TMUX CONF
unbind r
bind r source-file ~/.tmux.conf

#### KEYBIND FOR KILLING CURRENT
#### TMUX WINDOW PANE
bind x kill-pane

#### REBIND SPLIT WINDOW CMDS
bind j split-window -h
bind k split-window -v

#### UNBIND SPLIT-WINDOW CMDS
unbind '"'
unbind %

#### TMUX COPY & PASTE
#### KEYBINDINGS
setw -g mode-keys vi

#### ENTER VI-COPY-MODE
bind c copy-mode

#### PASTE BUFFER KEYBIND
bind v paste-buffer -p

#### LEFT AND RIGHT PANE 
#### SWITCHING BINDS
bind h select-pane -L
bind l select-pane -R

#### TOP AND DOWN PANE 
#### SWITCHING BINDS
bind i select-pane -U
bind m select-pane -D

#### CONFIGURE REPEAT TIME
set -g repeat-time 1000

#### TOP AND DOWN PANE 
#### RESIZING BINDS 
bind -n -r M-i resize-pane -U
bind -n -r M-m resize-pane -D

#### LEFT AND RIGHT PANE 
#### RESIZING BINDS
bind -n -r M-h resize-pane -L
bind -n -r M-l resize-pane -R

#### BINDINGS FOR WINDOW SELECTION
##bind F1 selectw -t:10
##bind F2 selectw -t:11
##bind F3 selectw -t:12
##bind F4 selectw -t:13
##bind F5 selectw -t:14
##bind F6 selectw -t:15
##bind F7 selectw -t:16
##bind F8 selectw -t:17
##bind F9 selectw -t:18
##bind F10 selectw -t:19
##bind F11 selectw -t:20
##bind F12 selectw -t:21

#### TOGGLE BETWEEN SMALLEST AND LARGEST 
#### INSTANCE OF A WINDOWS 
bind F set -w window-size
